"use client";

import { useState } from "react";
import { FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { api } from "@/lib/api";
import { printPdfBlob } from "@/lib/print-pdf";
import type { LandbasePeme } from "@/components/landbase/types";

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080";

/** Resolve a photo URL — prepends the API base if it's a relative path. */
function resolvePhotoUrl(url: string | undefined): string {
  if (!url) return "";
  if (url.startsWith("http")) return url;
  return `${API_BASE}${url}`;
}

/**
 * Memoizes resolved photo → base64 conversions so printing several reports for
 * the same record (or reprinting one) reuses a single fetch + encode instead of
 * paying that round-trip on every print.
 */
const photoBase64Cache = new Map<string, Promise<string>>();

/**
 * Fetches an image from a URL and returns it as a base64 data URL.
 * Returns empty string if the fetch fails or the URL is empty.
 */
function fetchPhotoAsBase64(url: string | undefined): Promise<string> {
  const resolved = resolvePhotoUrl(url);
  if (!resolved) return Promise.resolve("");

  const cached = photoBase64Cache.get(resolved);
  if (cached) return cached;

  const request = (async () => {
    try {
      const response = await fetch(resolved);
      if (!response.ok) return "";

      const blob = await response.blob();
      return await new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = () => resolve("");
        reader.readAsDataURL(blob);
      });
    } catch {
      return "";
    }
  })();

  // Cache the in-flight promise so concurrent/repeat calls dedupe; drop it on a
  // failed/empty result so a later retry can succeed.
  photoBase64Cache.set(resolved, request);
  void request.then((value) => {
    if (!value) photoBase64Cache.delete(resolved);
  });

  return request;
}

/**
 * Landbase report options.
 *
 * The MLC certificate is generated via PrintIO (client builds a flat payload and
 * posts to the Next.js print route). The remaining reports are generated by the
 * backend JasperReports service via `generateReport`.
 */
const REPORT_OPTIONS = [
  {
    slug: "landbase-mlc",
    label: "MLC Certificate",
    description: "Maritime Labour Convention medical certificate",
    engine: "printio",
  },
  {
    slug: "landbase-summary",
    label: "Summary Report",
    description: "Results and recommendation overview",
    engine: "printio",
  },
  {
    slug: "landbase-detailed",
    label: "Detailed Report",
    description: "Complete PEME with all sections",
    engine: "printio",
  },
  {
    slug: "landbase-mer",
    label: "MER Form",
    description: "Medical Examination Report",
    engine: "backend",
  },
] as const;

interface PrintDialogProps {
  /** Whether the dialog is open. */
  open: boolean;
  /** Callback when the dialog should close. */
  onClose: () => void;
  /** UUID of the current PEME record. Null when no record is loaded. */
  pemeId: string | undefined;
  /** Current PEME form data, used to build the PrintIO payload. */
  data: LandbasePeme | null;
}

/** Convert a boolean to the "Adequate"/"Defective" convention used by the MLC template. */
const colorVision = (adequate: boolean | undefined): string =>
  adequate ? "Adequate" : "Defective";

/**
 * Read a medical-history condition and convert it to the "true"/"false" string
 * convention the detailed template expects. Missing/empty keys coalesce to "".
 */
const history = (data: LandbasePeme, key: string): string => {
  const value = data.medical_history?.[key];
  if (value === "yes") return "true";
  if (value === "no") return "false";
  return "";
};

/**
 * Physical-exploration status for the detailed template. The template expects
 * the raw "N"/"A" code; empty values coalesce to "".
 */
const peStatus = (value: string | undefined): string =>
  value === "N" || value === "A" ? value : "";

/**
 * Builds the PrintIO payload for the landbase MLC medical certificate.
 *
 * Flattens the PEME record into the flat template variable names expected by
 * the PrintIO MLC template. The patient photo is fetched from the linked
 * seafarer profile and embedded inline as a base64 data URL.
 */
async function buildMlcPayload(data: LandbasePeme): Promise<Record<string, string>> {
  const fullName = [data.first_name, data.middle_name, data.last_name]
    .filter(Boolean)
    .join(" ")
    .trim();

  const photoBase64 = await fetchPhotoAsBase64(data.photo_url);

  return {
    // Identity / personal information
    last_name: data.last_name ?? "",
    first_name: data.first_name ?? "",
    middle_name: data.middle_name ?? "",
    age: "",
    birthdate: "",
    place_of_birth: data.place_of_birth ?? "",
    nationality: data.nationality ?? "",
    gender: data.gender ?? "",
    marital_status: data.civil_status ?? "",
    religion: data.religion ?? "",
    address: data.address ?? "",
    passport_no: data.passport_no ?? "",
    country_of_destination: "",
    position: data.position ?? "",
    employer: data.employer ?? "",

    // Assessment results
    hearing_satisfactory: data.hearing_satisfactory ?? "",
    vision_satisfactory_sight: data.vision_satisfactory_sight ?? "",
    vision_color_adequate: colorVision(data.vision_color_adequate),
    psychological_satisfactory: data.psychological_satisfactory ?? "",
    recommendation: data.recommendation ?? "",

    // Certification
    nameOfPatient: fullName,
    authorized_physician: data.authorized_physician ?? "",
    date_initial_peme: data.date_initial_peme ?? "",
    medical_director: data.medical_director ?? "",
    date_of_fitness: data.date_of_fitness ?? "",
    valid_until: data.valid_until ?? "",
    medical_certification_no: data.medical_certification_no ?? "",
    photo_url: photoBase64,
  };
}

/**
 * Builds the PrintIO payload for the landbase summary report.
 *
 * Flattens the PEME record into the flat template variable names expected by
 * the PrintIO summary template. The patient photo is fetched from the linked
 * seafarer profile and embedded inline as a base64 data URL.
 *
 * NOTE: `age`, `birthdate`, `country_of_destination`, and `suffering` have no
 * corresponding field on the PEME model and are sent as empty strings until a
 * data source is available.
 */
async function buildSummaryPayload(data: LandbasePeme): Promise<Record<string, string>> {
  const fullName = [data.first_name, data.middle_name, data.last_name]
    .filter(Boolean)
    .join(" ")
    .trim();

  const photoBase64 = await fetchPhotoAsBase64(data.photo_url);

  return {
    // Identity / personal information
    last_name: data.last_name ?? "",
    first_name: data.first_name ?? "",
    middle_name: data.middle_name ?? "",
    age: "",
    birthdate: "",
    place_of_birth: data.place_of_birth ?? "",
    nationality: data.nationality ?? "",
    gender: data.gender ?? "",
    marital_status: data.civil_status ?? "",
    religion: data.religion ?? "",
    address: data.address ?? "",
    passport_no: data.passport_no ?? "",
    position: data.position ?? "",
    country_of_destination: "",
    employer: data.employer ?? "",

    // Assessment results
    hearing_satisfactory: data.hearing_satisfactory ?? "",
    vision_satisfactory_sight: data.vision_satisfactory_sight ?? "",
    vision_color_adequate: colorVision(data.vision_color_adequate),
    vision_visual_aid: data.vision_visual_aid,

    // Certification
    nameOfPatient: fullName,
    recommendation: data.recommendation ?? "",
    authorized_physician: data.authorized_physician ?? "",
    date_initial_peme: data.date_initial_peme ?? "",
    medical_director: data.medical_director ?? "",
    date_of_fitness: data.date_of_fitness ?? "",
    valid_until: data.valid_until ?? "",
    photo_url: photoBase64,
  };
}

/**
 * Builds the PrintIO payload for the landbase detailed report.
 *
 * Flattens the full PEME record into the flat template variable names expected
 * by the PrintIO detailed template: personal info, the past-medical-history
 * questionnaire (read from the `medical_history` map using the same keys the
 * form writes), vision/hearing, per-body-system physical examination status +
 * findings, ancillary lab results, vital signs, and certification. The patient
 * photo is fetched from the linked seafarer profile and embedded inline as a
 * base64 data URL.
 *
 * `age`, `birthdate`, `seamans_book_no`, and `country_of_destination` are
 * sourced from the linked seafarer profile (flattened onto the PEME record).
 * `field27` has no data source and is sent as an empty string.
 */
async function buildDetailedPayload(data: LandbasePeme): Promise<Record<string, string>> {
  const photoBase64 = await fetchPhotoAsBase64(data.photo_url);

  return {
    // Identity / personal information
    photo_url: photoBase64,
    last_name: data.last_name ?? "",
    first_name: data.first_name ?? "",
    middle_name: data.middle_name ?? "",
    place_of_birth: data.place_of_birth ?? "",
    age: data.age ?? "",
    birthdate: data.birthdate ?? "",
    gender: data.gender ?? "",
    marital_status: data.civil_status ?? "",
    religion: data.religion ?? "",
    nationality: data.nationality ?? "",
    address: data.address ?? "",
    passport_no: data.passport_no ?? "",
    seamans_book_no: data.seamans_book_no ?? "",
    employer: data.employer ?? "",
    country_of_destination: data.country_of_destination ?? "",
    contact_no: data.contact_no ?? "",
    position: data.position ?? "",
    ref_no: data.peme_id ?? "",

    // I. Past Medical History (read from the medical_history map by exact key)
    head_or_neck_injury: history(data, "Head or Neck Injury"),
    frequent_headaches: history(data, "Frequent Headaches"),
    frequent_dizziness: history(data, "Frequent Dizziness"),
    fainting_spells_fits_seizures_or_other_neurological_disorders: history(
      data,
      "Fainting Spells, Fits, Seizures or other Neurological Disorders",
    ),
    insomnia_or_sleep_disorders_manias_phobias: history(
      data,
      "Insomnia or sleep disorders, Manias, Phobias",
    ),
    depression_other_mental_disorders: history(data, "Depression, other Mental Disorders"),
    trachoma_other_eye_disorders: history(data, "Trachoma, other eye Disorders"),
    deafness_other_ear_disorders: history(data, "Deafness, other Ear Disorders"),
    nose_or_throat_disorders: history(data, "Nose or Throat Disorders"),
    tuberculosis: history(data, "Tuberculosis"),
    other_lung_disorders: history(data, "Other Lung Disorders"),
    high_blood_pressure: history(data, "High Blood Pressure"),
    heart_disease_heart_pain: history(data, "Heart Disease/Heart Pain"),
    rheumatic_fever: history(data, "Rheumatic Fever"),
    diabetes_mellitus: history(data, "Diabetes Mellitus"),
    other_endocrine_disorders: history(data, "Other Endocrine Disorders (e.g. Goiter)"),
    cancer_or_tumor: history(data, "Cancer or Tumor"),
    blood_disorders: history(data, "Blood Disorders"),
    stomach_pain_gastritis_or_ulcer: history(data, "Stomach Pain, Gastritis or Ulcer"),
    other_abdominal_disorders: history(data, "Other Abdominal Disorders"),
    kidney_or_bladder_disorder: history(data, "Kidney or Bladder Disorder"),
    back_injury_joint_pain_arthritis_rheumatism: history(
      data,
      "Back Injury: Joint Pain/Arthritis/Rheumatism",
    ),
    genetic_hereditary_or_familial_disorders: history(
      data,
      "Genetic, Hereditary or Familial Disorders",
    ),
    sexually_transmitted_diseases: history(data, "Sexually Transmitted Diseases"),
    tropical_diseases: history(data, "Tropical Diseases"),
    asthma: history(data, "Asthma"),
    allergies: history(data, "Allergies (Specify):"),
    gynecological_disorder: history(data, "Gynecological Disorder (For female)"),
    operations: history(data, "Operations (Specify)"),
    // No corresponding model field
    field27: "",
    consulted_doctor_details: data.consulted_doctor_details ?? "",
    maintenance_medications: data.maintenance_medications ?? "",

    // II. Physical Examination - vision
    vision_far_od_uncorrected: data.vision_far_od_uncorrected ?? "",
    vision_far_od_corrected: data.vision_far_od_corrected ?? "",
    vision_far_os_uncorrected: data.vision_far_os_uncorrected ?? "",
    vision_far_os_corrected: data.vision_far_os_corrected ?? "",
    vision_near_od_uncorrected: data.vision_near_od_uncorrected ?? "",
    vision_near_od_corrected: data.vision_near_od_corrected ?? "",
    vision_near_os_uncorrected: data.vision_near_os_uncorrected ?? "",
    vision_near_os_corrected: data.vision_near_os_corrected ?? "",
    vision_color_adequate: colorVision(data.vision_color_adequate),
    hearing_ad: data.hearing_ad ?? "",
    hearing_as: data.hearing_as ?? "",

    // II. Physical Examination - body-system status
    pe_skin: peStatus(data.pe_skin),
    pe_head_scalp: peStatus(data.pe_head_scalp),
    pe_eyes_external: peStatus(data.pe_eyes_external),
    pe_pupils: peStatus(data.pe_pupils),
    pe_ears: peStatus(data.pe_ears),
    pe_nose_sinuses: peStatus(data.pe_nose_sinuses),
    pe_mouth_throat: peStatus(data.pe_mouth_throat),
    pe_neck_lymph_nodes: peStatus(data.pe_neck_lymph_nodes),
    pe_breast_axilla: peStatus(data.pe_breast_axilla),
    pe_chest_lungs: peStatus(data.pe_chest_lungs),
    pe_heart: peStatus(data.pe_heart),
    pe_abdomen: peStatus(data.pe_abdomen),
    pe_back: peStatus(data.pe_back),
    pe_anus_rectum: peStatus(data.pe_anus_rectum),
    pe_genito_urinary: peStatus(data.pe_genito_urinary),
    pe_inguinals_genitals: peStatus(data.pe_inguinals_genitals),
    pe_extremities: peStatus(data.pe_extremities),
    pe_reflexes: peStatus(data.pe_reflexes),
    pe_dental: peStatus(data.pe_dental),

    // II. Physical Examination - body-system findings
    pe_skin_findings: data.pe_skin_findings ?? "",
    pe_head_scalp_findings: data.pe_head_scalp_findings ?? "",
    pe_eyes_external_findings: data.pe_eyes_external_findings ?? "",
    pe_pupils_findings: data.pe_pupils_findings ?? "",
    pe_ears_findings: data.pe_ears_findings ?? "",
    pe_nose_sinuses_findings: data.pe_nose_sinuses_findings ?? "",
    pe_mouth_throat_findings: data.pe_mouth_throat_findings ?? "",
    pe_neck_lymph_nodes_findings: data.pe_neck_lymph_nodes_findings ?? "",
    pe_breast_axilla_findings: data.pe_breast_axilla_findings ?? "",
    pe_chest_lungs_findings: data.pe_chest_lungs_findings ?? "",
    pe_heart_findings: data.pe_heart_findings ?? "",
    pe_abdomen_findings: data.pe_abdomen_findings ?? "",
    pe_back_findings: data.pe_back_findings ?? "",
    pe_anus_rectum_findings: data.pe_anus_rectum_findings ?? "",
    pe_genito_urinary_findings: data.pe_genito_urinary_findings ?? "",
    pe_inguinals_genitals_findings: data.pe_inguinals_genitals_findings ?? "",
    pe_extremities_findings: data.pe_extremities_findings ?? "",
    pe_reflexes_findings: data.pe_reflexes_findings ?? "",
    pe_dental_findings: data.pe_dental_findings ?? "",

    // II. Physical Examination - vital signs
    pe_weight: data.pe_weight ?? "",
    pe_height: data.pe_height ?? "",
    pe_bmi: data.pe_bmi ?? "",
    pe_pulse_rate: data.pe_pulse_rate ?? "",
    pe_blood_pressure: data.pe_blood_pressure ?? "",
    pe_respiration: data.pe_respiration ?? "",
    pe_body_temperature: data.pe_body_temperature ?? "",

    // III. Ancillary Examinations
    xray_no: data.xray_no ?? "",
    chest_xray: data.chest_xray ?? "",
    cec: data.cec ?? "",
    cbc: data.cbc ?? "",
    pregnancy_test: data.pregnancy_test ?? "",
    urinalysis: data.urinalysis ?? "",
    stool_exam: data.stool_exam ?? "",
    hbsag: data.hbsag ?? "",
    hiv_aids_test: data.hiv_aids_test ?? "",
    apb: data.apb ?? "",
    blood_type: data.blood_type ?? "",
    psychological_test: data.psychological_test ?? "",
    additional_tests: data.additional_tests ?? "",

    // Remarks / recommendation / certification
    remarks: data.remarks ?? "",
    recommendation: data.recommendation ?? "",
    date_initial_peme: data.date_initial_peme ?? "",
    date_of_fitness: data.date_of_fitness ?? "",
    valid_until: data.valid_until ?? "",
    authorized_physician: data.authorized_physician ?? "",
    medical_director: data.medical_director ?? "",
  };
}

/**
 * Dialog that lets the user choose which landbase report to generate.
 *
 * The MLC certificate is generated via PrintIO: the client builds a flat payload
 * from the current record, posts it to the Next.js print route, and opens the
 * browser print dialog for the returned PDF. The remaining reports are generated
 * by the backend and opened in a new tab.
 */
export function PrintDialog({ open, onClose, pemeId, data }: PrintDialogProps) {
  const [generating, setGenerating] = useState<string | null>(null);

  const handleBackendReport = async (slug: string) => {
    if (!pemeId) {
      toast.error("No PEME record loaded. Please select or save a record first.");
      return;
    }
    await api.entities.LandbasePeme.generateReport(pemeId, slug);
    onClose();
  };

  const handlePrintioReport = async (slug: string) => {
    if (!data || !data.last_name) {
      toast.error("No PEME record loaded. Please select or save a record first.");
      return;
    }

    let payload: Record<string, string>;
    if (slug === "landbase-summary") {
      payload = await buildSummaryPayload(data);
    } else if (slug === "landbase-detailed") {
      payload = await buildDetailedPayload(data);
    } else {
      payload = await buildMlcPayload(data);
    }

    const response = await fetch(`/api/print/${slug}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      let message = "Failed to generate report";
      try {
        const errorBody = await response.json();
        if (errorBody.message) message = errorBody.message;
      } catch {
        // Ignore parse errors
      }
      throw new Error(message);
    }

    const blob = await response.blob();
    await printPdfBlob(blob);
    onClose();
  };

  const handleGenerate = async (option: (typeof REPORT_OPTIONS)[number]) => {
    setGenerating(option.slug);
    try {
      if (option.engine === "printio") {
        await handlePrintioReport(option.slug);
      } else {
        await handleBackendReport(option.slug);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to generate report";
      toast.error(message);
    } finally {
      setGenerating(null);
    }
  };

  const hasRecord = !!pemeId || !!data?.last_name;

  return (
    <Dialog open={open} onOpenChange={(isOpen) => { if (!isOpen) onClose(); }}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Print Report</DialogTitle>
          <DialogDescription>
            Select which report to generate for this PEME record.
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-2 py-2">
          {REPORT_OPTIONS.map((option) => {
            const disabled =
              generating !== null ||
              (option.engine === "printio" ? !data?.last_name : !pemeId);
            return (
              <Button
                key={option.slug}
                variant="outline"
                className="h-auto justify-start gap-3 px-4 py-3 text-left"
                disabled={disabled}
                onClick={() => handleGenerate(option)}
              >
                {generating === option.slug ? (
                  <Loader2 className="h-4 w-4 shrink-0 animate-spin text-primary" />
                ) : (
                  <FileText className="h-4 w-4 shrink-0 text-primary" />
                )}
                <div className="flex flex-col">
                  <span className="text-sm font-medium">{option.label}</span>
                  <span className="text-xs text-muted-foreground">{option.description}</span>
                </div>
              </Button>
            );
          })}
        </div>

        {!hasRecord && (
          <p className="text-xs text-destructive">
            No record loaded. Search for a patient or save a new record to enable printing.
          </p>
        )}
      </DialogContent>
    </Dialog>
  );
}
