/**
 * Predefined suggestion lists for autocomplete fields across the profile form.
 *
 * These are common values in the maritime/seafarer domain. Users can still
 * type free-form text — these just speed up data entry.
 */

/** Nationality suggestions for the seafarer profile nationality field. */
export const NATIONALITIES = [
  "Filipino",
  "American",
  "Australian",
  "Bangladeshi",
  "Brazilian",
  "British",
  "Burmese",
  "Canadian",
  "Chinese",
  "Croatian",
  "Danish",
  "Dutch",
  "Egyptian",
  "French",
  "German",
  "Greek",
  "Indian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Malaysian",
  "Mexican",
  "Nigerian",
  "Norwegian",
  "Pakistani",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Saudi",
  "Singaporean",
  "South African",
  "Spanish",
  "Sri Lankan",
  "Swedish",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Vietnamese",
];

/** Religion suggestions for the profile religion field. */
export const RELIGIONS = [
  "Roman Catholic",
  "Islam",
  "Iglesia ni Cristo",
  "Protestant",
  "Evangelical",
  "Born Again Christian",
  "Seventh Day Adventist",
  "Baptist",
  "Methodist",
  "Church of Christ",
  "Jehovah's Witness",
  "Buddhist",
  "Hindu",
  "Others",
];

/** Shipboard rank/position suggestions for the profile position field. */
export const POSITIONS = [
  "Able Seaman",
  "Bosun",
  "Captain",
  "Cadet",
  "Chief Cook",
  "Chief Engineer",
  "Chief Mate",
  "Chief Officer",
  "Deck Cadet",
  "Electrician",
  "Engine Cadet",
  "Fitter",
  "Fourth Engineer",
  "Messman",
  "Oiler",
  "Ordinary Seaman",
  "Pump Man",
  "Radio Officer",
  "Second Engineer",
  "Second Mate",
  "Second Officer",
  "Steward",
  "Third Engineer",
  "Third Mate",
  "Third Officer",
  "Wiper",
];

/** Country suggestions for address/nationality-related profile fields. */
export const COUNTRIES = [
  "Philippines",
  "United States",
  "Australia",
  "Bangladesh",
  "Brazil",
  "Canada",
  "China",
  "Croatia",
  "Denmark",
  "Egypt",
  "France",
  "Germany",
  "Greece",
  "India",
  "Indonesia",
  "Italy",
  "Japan",
  "Malaysia",
  "Mexico",
  "Netherlands",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Panama",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Vietnam",
];

/** City suggestions (Philippine cities) for profile address fields. */
export const CITIES = [
  "Manila",
  "Cebu City",
  "Davao City",
  "Quezon City",
  "Makati",
  "Pasig",
  "Taguig",
  "Caloocan",
  "Zamboanga City",
  "Antipolo",
  "Iloilo City",
  "Bacolod",
  "General Santos",
  "Cagayan de Oro",
  "Parañaque",
  "Las Piñas",
  "Muntinlupa",
  "Valenzuela",
  "Baguio",
  "Batangas City",
  "Olongapo",
  "Subic",
  "Angeles City",
  "San Fernando",
  "Tacloban",
  "Legazpi",
  "Naga",
  "Puerto Princesa",
  "Butuan",
  "Cotabato City",
];

// Employer suggestions are sourced from the database via the `useEmployers`
// hook (GET /api/employers). See frontend/src/hooks/use-employers.ts.

/** Crew designation/category suggestions for the profile designation field. */
export const DESIGNATIONS = [
  "Seafarer",
  "Officer",
  "Rating",
  "Deck Officer",
  "Engine Officer",
  "Deck Rating",
  "Engine Rating",
  "Catering",
  "Trainee",
  "Supernumerary",
];

/** Educational course/program suggestions for the profile education fields. */
export const COURSES = [
  "BS Marine Transportation",
  "BS Marine Engineering",
  "BS Naval Architecture",
  "BS Customs Administration",
  "BS Information Technology",
  "BS Computer Science",
  "BS Mechanical Engineering",
  "BS Electrical Engineering",
  "BS Electronics Engineering",
  "BS Civil Engineering",
  "BS Nursing",
  "BS Accountancy",
  "BS Business Administration",
  "BS Hotel & Restaurant Management",
  "BS Tourism Management",
  "Associate in Marine Transportation",
  "Associate in Marine Engineering",
  "Vocational / TESDA",
  "Others",
];
