/**
 * Predefined suggestion lists for autocomplete fields across the profile form.
 *
 * These are common values in the maritime/seafarer domain. Users can still
 * type free-form text — these just speed up data entry.
 */

export const NATIONALITIES = [
  "Filipino",
  "American",
  "Australian",
  "Bangladeshi",
  "Brazilian",
  "British",
  "Burmese",
  "Canadian",
  "Chinese",
  "Croatian",
  "Danish",
  "Dutch",
  "Egyptian",
  "French",
  "German",
  "Greek",
  "Indian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Malaysian",
  "Mexican",
  "Nigerian",
  "Norwegian",
  "Pakistani",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Saudi",
  "Singaporean",
  "South African",
  "Spanish",
  "Sri Lankan",
  "Swedish",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Vietnamese",
];

export const RELIGIONS = [
  "Roman Catholic",
  "Islam",
  "Iglesia ni Cristo",
  "Protestant",
  "Evangelical",
  "Born Again Christian",
  "Seventh Day Adventist",
  "Baptist",
  "Methodist",
  "Church of Christ",
  "Jehovah's Witness",
  "Buddhist",
  "Hindu",
  "Others",
];

export const POSITIONS = [
  "Able Seaman",
  "Bosun",
  "Captain",
  "Cadet",
  "Chief Cook",
  "Chief Engineer",
  "Chief Mate",
  "Chief Officer",
  "Deck Cadet",
  "Electrician",
  "Engine Cadet",
  "Fitter",
  "Fourth Engineer",
  "Messman",
  "Oiler",
  "Ordinary Seaman",
  "Pump Man",
  "Radio Officer",
  "Second Engineer",
  "Second Mate",
  "Second Officer",
  "Steward",
  "Third Engineer",
  "Third Mate",
  "Third Officer",
  "Wiper",
];

export const COUNTRIES = [
  "Philippines",
  "United States",
  "Australia",
  "Bangladesh",
  "Brazil",
  "Canada",
  "China",
  "Croatia",
  "Denmark",
  "Egypt",
  "France",
  "Germany",
  "Greece",
  "India",
  "Indonesia",
  "Italy",
  "Japan",
  "Malaysia",
  "Mexico",
  "Netherlands",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Panama",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Vietnam",
];

export const CITIES = [
  "Manila",
  "Cebu City",
  "Davao City",
  "Quezon City",
  "Makati",
  "Pasig",
  "Taguig",
  "Caloocan",
  "Zamboanga City",
  "Antipolo",
  "Iloilo City",
  "Bacolod",
  "General Santos",
  "Cagayan de Oro",
  "Parañaque",
  "Las Piñas",
  "Muntinlupa",
  "Valenzuela",
  "Baguio",
  "Batangas City",
  "Olongapo",
  "Subic",
  "Angeles City",
  "San Fernando",
  "Tacloban",
  "Legazpi",
  "Naga",
  "Puerto Princesa",
  "Butuan",
  "Cotabato City",
];

export const EMPLOYERS = [
  "Magsaysay Maritime",
  "NYK-Fil Ship Management",
  "Marlow Navigation",
  "Anglo-Eastern",
  "V.Ships",
  "BSM (Bernhard Schulte Shipmanagement)",
  "Döhle Seafront",
  "OSM Maritime",
  "Synergy Marine",
  "Thome Ship Management",
  "Fleet Management Limited",
  "Wilhelmsen Ship Management",
  "Columbia Shipmanagement",
  "CF Sharp Crew Management",
  "Jebsen Maritime",
  "Pacific Basin Shipping",
  "Eastern Pacific Shipping",
  "Oceanic Marine Contractors",
  "United Philippine Lines",
  "Philippine Transmarine Carriers",
];

export const DESIGNATIONS = [
  "Seafarer",
  "Officer",
  "Rating",
  "Deck Officer",
  "Engine Officer",
  "Deck Rating",
  "Engine Rating",
  "Catering",
  "Trainee",
  "Supernumerary",
];

export const COURSES = [
  "BS Marine Transportation",
  "BS Marine Engineering",
  "BS Naval Architecture",
  "BS Customs Administration",
  "BS Information Technology",
  "BS Computer Science",
  "BS Mechanical Engineering",
  "BS Electrical Engineering",
  "BS Electronics Engineering",
  "BS Civil Engineering",
  "BS Nursing",
  "BS Accountancy",
  "BS Business Administration",
  "BS Hotel & Restaurant Management",
  "BS Tourism Management",
  "Associate in Marine Transportation",
  "Associate in Marine Engineering",
  "Vocational / TESDA",
  "Others",
];
